# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T11:29:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel, SecretStr, conint, constr


class AccessDeniedException(RootModel[Any]):
    root: Any


class DataBundleArn(
    RootModel[
        constr(
            pattern=r'^arn:aws:finspace:[A-Za-z0-9_/.-]{0,63}:\d*:data-bundle/[0-9A-Za-z_-]{1,128}$',
            min_length=20,
            max_length=2048,
        )
    ]
):
    root: constr(
        pattern=r'^arn:aws:finspace:[A-Za-z0-9_/.-]{0,63}:\d*:data-bundle/[0-9A-Za-z_-]{1,128}$',
        min_length=20,
        max_length=2048,
    ) = Field(..., description='The Amazon Resource Name (ARN) of the data bundle.')


class DataBundleArns(RootModel[List[DataBundleArn]]):
    root: List[DataBundleArn]


class DeleteEnvironmentRequest(BaseModel):
    pass


class DeleteEnvironmentResponse(BaseModel):
    pass


class Description(
    RootModel[constr(pattern=r'^[a-zA-Z0-9. ]{1,1000}$', min_length=1, max_length=1000)]
):
    root: constr(pattern=r'^[a-zA-Z0-9. ]{1,1000}$', min_length=1, max_length=1000)


class EmailId(RootModel[SecretStr]):
    root: SecretStr


class EnvironmentArn(
    RootModel[
        constr(
            pattern=r'^arn:aws:finspace:[A-Za-z0-9_/.-]{0,63}:\d+:environment/[0-9A-Za-z_-]{1,128}$',
            min_length=20,
            max_length=2048,
        )
    ]
):
    root: constr(
        pattern=r'^arn:aws:finspace:[A-Za-z0-9_/.-]{0,63}:\d+:environment/[0-9A-Za-z_-]{1,128}$',
        min_length=20,
        max_length=2048,
    )


class EnvironmentName(
    RootModel[
        constr(
            pattern=r'^[a-zA-Z0-9]+[a-zA-Z0-9-]*[a-zA-Z0-9]$',
            min_length=1,
            max_length=255,
        )
    ]
):
    root: constr(
        pattern=r'^[a-zA-Z0-9]+[a-zA-Z0-9-]*[a-zA-Z0-9]$', min_length=1, max_length=255
    )


class EnvironmentStatus(Enum):
    CREATE_REQUESTED = 'CREATE_REQUESTED'
    CREATING = 'CREATING'
    CREATED = 'CREATED'
    DELETE_REQUESTED = 'DELETE_REQUESTED'
    DELETING = 'DELETING'
    DELETED = 'DELETED'
    FAILED_CREATION = 'FAILED_CREATION'
    RETRY_DELETION = 'RETRY_DELETION'
    FAILED_DELETION = 'FAILED_DELETION'
    SUSPENDED = 'SUSPENDED'


class FederationAttributeKey(
    RootModel[constr(pattern=r'.*', min_length=1, max_length=32)]
):
    root: constr(pattern=r'.*', min_length=1, max_length=32)


class FederationMode(Enum):
    FEDERATED = 'FEDERATED'
    LOCAL = 'LOCAL'


class FederationProviderName(
    RootModel[
        constr(
            pattern=r'[^_\p{Z}][\p{L}\p{M}\p{S}\p{N}\p{P}][^_\p{Z}]+',
            min_length=1,
            max_length=32,
        )
    ]
):
    root: constr(
        pattern=r'[^_\p{Z}][\p{L}\p{M}\p{S}\p{N}\p{P}][^_\p{Z}]+',
        min_length=1,
        max_length=32,
    )


class GetEnvironmentRequest(BaseModel):
    pass


class IdType(
    RootModel[constr(pattern=r'^[a-zA-Z0-9]{1,26}$', min_length=1, max_length=26)]
):
    root: constr(pattern=r'^[a-zA-Z0-9]{1,26}$', min_length=1, max_length=26)


class InternalServerException(RootModel[Any]):
    root: Any


class InvalidRequestException(RootModel[Any]):
    root: Any


class KmsKeyId(
    RootModel[constr(pattern=r'^[a-zA-Z-0-9-:\/]*$', min_length=1, max_length=1000)]
):
    root: constr(pattern=r'^[a-zA-Z-0-9-:\/]*$', min_length=1, max_length=1000)


class LimitExceededException(RootModel[Any]):
    root: Any


class ListEnvironmentsRequest(BaseModel):
    pass


class ListTagsForResourceRequest(BaseModel):
    pass


class NameString(
    RootModel[constr(pattern=r'^[a-zA-Z0-9]{1,50}$', min_length=1, max_length=50)]
):
    root: constr(pattern=r'^[a-zA-Z0-9]{1,50}$', min_length=1, max_length=50)


class PaginationToken(RootModel[constr(pattern=r'.*', min_length=1, max_length=1000)]):
    root: constr(pattern=r'.*', min_length=1, max_length=1000)


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class ResultLimit(RootModel[conint(ge=0, le=100)]):
    root: conint(ge=0, le=100)


class SamlMetadataDocument(
    RootModel[constr(pattern=r'.*', min_length=1000, max_length=10000000)]
):
    root: constr(pattern=r'.*', min_length=1000, max_length=10000000)


class ServiceQuotaExceededException(RootModel[Any]):
    root: Any


class SmsDomainUrl(
    RootModel[constr(pattern=r'^[a-zA-Z-0-9-:\/.]*$', min_length=1, max_length=1000)]
):
    root: constr(pattern=r'^[a-zA-Z-0-9-:\/.]*$', min_length=1, max_length=1000)


class SuperuserParameters(BaseModel):
    emailAddress: EmailId
    firstName: NameString
    lastName: NameString


class TagKey(
    RootModel[
        constr(pattern=r'^(?!aws:)[a-zA-Z+-=._:/]+$', min_length=1, max_length=128)
    ]
):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(pattern=r'^(?!aws:)[a-zA-Z+-=._:/]+$', min_length=1, max_length=128)


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=50, min_length=1)


class TagResourceResponse(BaseModel):
    pass


class TagValue(
    RootModel[constr(pattern=r'^[a-zA-Z0-9+-=._:@ ]+$', min_length=1, max_length=256)]
):
    root: constr(pattern=r'^[a-zA-Z0-9+-=._:@ ]+$', min_length=1, max_length=256)


class ThrottlingException(RootModel[Any]):
    root: Any


class UntagResourceRequest(BaseModel):
    pass


class UntagResourceResponse(BaseModel):
    pass


class ValidationException(RootModel[Any]):
    root: Any


class Url(
    RootModel[
        constr(
            pattern=r'^https?://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]',
            min_length=1,
            max_length=1000,
        )
    ]
):
    root: constr(
        pattern=r'^https?://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]',
        min_length=1,
        max_length=1000,
    )


class Urn(
    RootModel[constr(pattern=r'^[A-Za-z0-9._\-:\/#\+]+$', min_length=1, max_length=255)]
):
    root: constr(pattern=r'^[A-Za-z0-9._\-:\/#\+]+$', min_length=1, max_length=255)


class SuperuserParameters1(BaseModel):
    emailAddress: Optional[EmailId] = None
    firstName: Optional[NameString] = None
    lastName: Optional[NameString] = None


class TagsResourceArnPostRequest(BaseModel):
    tags: Dict[str, TagValue] = Field(
        ..., description='One or more tags to be assigned to the resource.'
    )


class TagKeys(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=50, min_length=1)


class AttributeMap(RootModel[Optional[Dict[str, Url]]]):
    root: Optional[Dict[str, Url]] = None


class CreateEnvironmentResponse(BaseModel):
    environmentArn: Optional[EnvironmentArn] = None
    environmentId: Optional[IdType] = None
    environmentUrl: Optional[Url] = None


class FederationParameters(BaseModel):
    applicationCallBackURL: Optional[Url] = None
    attributeMap: Optional[AttributeMap] = None
    federationProviderName: Optional[FederationProviderName] = None
    federationURN: Optional[Urn] = None
    samlMetadataDocument: Optional[SamlMetadataDocument] = None
    samlMetadataURL: Optional[Url] = None


class TagMap(RootModel[Optional[Dict[str, TagValue]]]):
    root: Optional[Dict[str, TagValue]] = None


class TagResourceRequest(BaseModel):
    tags: TagMap


class UpdateEnvironmentRequest(BaseModel):
    description: Optional[Description] = None
    federationMode: Optional[FederationMode] = None
    federationParameters: Optional[FederationParameters] = None
    name: Optional[EnvironmentName] = None


class EnvironmentPostRequest(BaseModel):
    dataBundles: Optional[List[DataBundleArn]] = Field(
        None,
        description='<p>The list of Amazon Resource Names (ARN) of the data bundles to install. Currently supported data bundle ARNs:</p> <ul> <li> <p> <code>arn:aws:finspace:${Region}::data-bundle/capital-markets-sample</code> - Contains sample Capital Markets datasets, categories and controlled vocabularies.</p> </li> <li> <p> <code>arn:aws:finspace:${Region}::data-bundle/taq</code> (default) - Contains trades and quotes data in addition to sample Capital Markets data.</p> </li> </ul>',
    )
    description: Optional[
        constr(pattern=r'^[a-zA-Z0-9. ]{1,1000}$', min_length=1, max_length=1000)
    ] = Field(
        None, description='The description of the FinSpace environment to be created.'
    )
    federationMode: Optional[FederationMode] = Field(
        None,
        description='<p>Authentication mode for the environment.</p> <ul> <li> <p> <code>FEDERATED</code> - Users access FinSpace through Single Sign On (SSO) via your Identity provider.</p> </li> <li> <p> <code>LOCAL</code> - Users access FinSpace via email and password managed within the FinSpace environment.</p> </li> </ul>',
    )
    federationParameters: Optional[FederationParameters] = Field(
        None,
        description='Configuration information when authentication mode is FEDERATED.',
    )
    kmsKeyId: Optional[
        constr(pattern=r'^[a-zA-Z-0-9-:\/]*$', min_length=1, max_length=1000)
    ] = Field(
        None,
        description='The KMS key id to encrypt your data in the FinSpace environment.',
    )
    name: constr(
        pattern=r'^[a-zA-Z0-9]+[a-zA-Z0-9-]*[a-zA-Z0-9]$', min_length=1, max_length=255
    ) = Field(..., description='The name of the FinSpace environment to be created.')
    superuserParameters: Optional[SuperuserParameters1] = Field(
        None, description='Configuration information for the superuser.'
    )
    tags: Optional[Dict[str, TagValue]] = Field(
        None, description='Add tags to your FinSpace environment.'
    )


class EnvironmentEnvironmentIdPutRequest(BaseModel):
    description: Optional[
        constr(pattern=r'^[a-zA-Z0-9. ]{1,1000}$', min_length=1, max_length=1000)
    ] = Field(None, description='The description of the environment.')
    federationMode: Optional[FederationMode] = Field(
        None,
        description='<p>Authentication mode for the environment.</p> <ul> <li> <p> <code>FEDERATED</code> - Users access FinSpace through Single Sign On (SSO) via your Identity provider.</p> </li> <li> <p> <code>LOCAL</code> - Users access FinSpace via email and password managed within the FinSpace environment.</p> </li> </ul>',
    )
    federationParameters: Optional[FederationParameters] = Field(
        None,
        description='Configuration information when authentication mode is FEDERATED.',
    )
    name: Optional[
        constr(
            pattern=r'^[a-zA-Z0-9]+[a-zA-Z0-9-]*[a-zA-Z0-9]$',
            min_length=1,
            max_length=255,
        )
    ] = Field(None, description='The name of the environment.')


class CreateEnvironmentRequest(BaseModel):
    dataBundles: Optional[DataBundleArns] = None
    description: Optional[Description] = None
    federationMode: Optional[FederationMode] = None
    federationParameters: Optional[FederationParameters] = None
    kmsKeyId: Optional[KmsKeyId] = None
    name: EnvironmentName
    superuserParameters: Optional[SuperuserParameters] = None
    tags: Optional[TagMap] = None


class Environment(BaseModel):
    awsAccountId: Optional[IdType] = None
    dedicatedServiceAccountId: Optional[IdType] = None
    description: Optional[Description] = None
    environmentArn: Optional[EnvironmentArn] = None
    environmentId: Optional[IdType] = None
    environmentUrl: Optional[Url] = None
    federationMode: Optional[FederationMode] = None
    federationParameters: Optional[FederationParameters] = None
    kmsKeyId: Optional[KmsKeyId] = None
    name: Optional[EnvironmentName] = None
    sageMakerStudioDomainUrl: Optional[SmsDomainUrl] = None
    status: Optional[EnvironmentStatus] = None


class EnvironmentList(RootModel[List[Environment]]):
    root: List[Environment]


class GetEnvironmentResponse(BaseModel):
    environment: Optional[Environment] = None


class ListEnvironmentsResponse(BaseModel):
    environments: Optional[EnvironmentList] = None
    nextToken: Optional[PaginationToken] = None


class ListTagsForResourceResponse(BaseModel):
    tags: Optional[TagMap] = None


class UpdateEnvironmentResponse(BaseModel):
    environment: Optional[Environment] = None
